language: minimal

services:
  - docker

jobs:
  include:
    - stage: build
    script:
      - docker run --rm -it -v "$PWD":/app -w /app node:lts npm install
      - docker run --rm -it -v "$PWD":/app -w /app node:lts npm run build