name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: docker-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        docker run --rm -it -v "$PWD":/app -w /app node:lts npm install
        docker run --rm -it -v "$PWD":/app -w /app node:lts npm run build
